CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    MOBILE_NUMBER VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

-- Snowflake standard tables do not enforce ordinary UNIQUE indexes.
-- MuleForge performs the duplicate-email lookup in the API flow.
