const fs=require("node:fs"),path=require("node:path");
const targets=new Set(["gitlab","azure-devops","jenkins","bitbucket"]);
const muleSteps="mvn -B -DskipTests=false clean package -ntp";
function render(target){
  if(!targets.has(target))throw new Error("Unsupported native CI target: "+target);
  if(target==="gitlab")return "stages:\n  - validate\n  - test\n  - security\n  - package\n  - deploy\n\nvalidate:\n  stage: validate\n  image: maven:3.9-eclipse-temurin-17\n  script:\n    - test -f pom.xml\n    - test -f mule-artifact.json\n    - test -d src/main/mule\n    - test -d src/test/munit\n\ntest:\n  stage: test\n  image: maven:3.9-eclipse-temurin-17\n  script:\n    - "+muleSteps+"\n\nsecurity:\n  stage: security\n  image: node:22\n  script:\n    - npm install --no-save muleforge\n    - npx muleforge security-scan .\n\npackage:\n  stage: package\n  image: maven:3.9-eclipse-temurin-17\n  script:\n    - "+muleSteps+"\n  artifacts:\n    paths:\n      - target/*.jar\n\ndeploy:\n  stage: deploy\n  script:\n    - echo \"Deployment is environment-specific; configure Mule runtime credentials and target here.\"\n  when: manual\n";
  if(target==="azure-devops")return "trigger:\n- main\n\npool:\n  vmImage: ubuntu-latest\n\nsteps:\n- task: JavaToolInstaller@0\n  inputs:\n    versionSpec: '17'\n    jdkArchitectureOption: x64\n    jdkSourceOption: PreInstalled\n- script: |\n    test -f pom.xml\n    test -f mule-artifact.json\n    test -d src/main/mule\n    test -d src/test/munit\n  displayName: Validate Mule project\n- script: "+muleSteps+"\n  displayName: Build and test\n- script: |\n    npm install --no-save muleforge\n    npx muleforge security-scan .\n  displayName: Security scan\n- publish: \$(Build.SourcesDirectory)/target\n  artifact: mule-artifact\n";
  if(target==="jenkins")return "pipeline {\n  agent any\n  stages {\n    stage('Validate') { steps { sh 'test -f pom.xml && test -f mule-artifact.json && test -d src/main/mule && test -d src/test/munit' } }\n    stage('Build and Test') { steps { sh '"+muleSteps+"' } }\n    stage('Security') { steps { sh 'npm install --no-save muleforge && npx muleforge security-scan .' } }\n    stage('Package') { steps { archiveArtifacts artifacts: 'target/*.jar', fingerprint: true } }\n    stage('Deploy') { steps { echo 'Deployment is environment-specific; configure Mule runtime credentials and target here.' } }\n  }\n}\n";
  return "pipelines:\n  default:\n    - step:\n        name: Validate\n        image: maven:3.9-eclipse-temurin-17\n        script:\n          - test -f pom.xml\n          - test -f mule-artifact.json\n          - test -d src/main/mule\n          - test -d src/test/munit\n    - step:\n        name: Build and Test\n        image: maven:3.9-eclipse-temurin-17\n        script:\n          - "+muleSteps+"\n        artifacts:\n          - target/*.jar\n    - step:\n        name: Security\n        image: node:22\n        script:\n          - npm install --no-save muleforge\n          - npx muleforge security-scan .\n";
}
function writeNative(root,target){const names={gitlab:".gitlab-ci.yml","azure-devops":"azure-pipelines.yml",jenkins:"Jenkinsfile",bitbucket:"bitbucket-pipelines.yml"};const p=path.join(path.resolve(root),names[target]);fs.writeFileSync(p,render(target));return p;}
module.exports={render,writeNative};
