const fs = require("fs");
const path = require("path");
const readline = require("readline/promises");
const { stdin, stdout } = require("process");
const YAML = require("yaml");
const os = require("os");
const { spawnSync } = require("child_process");
const { buildRequirementModel, missingQuestions, writeDocumentation } = require("./requirement-model");

async function ask(question, fallback = "") {
  const rl = readline.createInterface({ input: stdin, output: stdout });
  const answer = (await rl.question(`${question}${fallback ? ` [${fallback}]` : ""}: `)).trim();
  rl.close();
  return answer || fallback;
}

const list = value => String(value || "").split(/,|\n/).map(v => v.trim()).filter(Boolean);

function normalizeBackendConnectors(value) {
  const text = String(value || "").toLowerCase();
  const connectors = ["http"];
  if (/snowflake/.test(text)) connectors.push("snowflake");
  else if (/\b(mysql|mariadb|postgres|postgresql|oracle|database|db)\b/.test(text)) connectors.push("database");
  if (/\b(sftp|file transfer)\b/.test(text)) connectors.push("sftp");
  if (/ibm\s*mq|queue manager/.test(text)) connectors.push("ibm-mq");
  if (/anypoint\s*mq/.test(text)) connectors.push("anypoint-mq");
  if (/object\s*store|objectstore|cache/.test(text)) connectors.push("object-store");
  if (connectors.length === 1 && text.trim()) {
    throw new Error(`Unsupported backend/connector description: ${value}. Supported examples: MySQL, PostgreSQL, Oracle, Snowflake, SFTP, IBM MQ, Anypoint MQ, Object Store.`);
  }
  return [...new Set(connectors)];
}
function parseOperations(value) {
  return list(value).map(item => {
    const m = item.match(/^(GET|POST|PUT|PATCH|DELETE)\s+(\/\S+)$/i);
    if (!m) throw new Error(`Invalid operation: ${item}. Use METHOD /path.`);
    return { method: m[1].toUpperCase(), path: m[2] };
  });
}

function printDesign(model) {
  console.log("\n=== MuleForge Solution Design ===");
  console.log(`Project: ${model.project.name}`);
  console.log(`API: ${model.api.type} ${model.api.basePath}`);
  console.log(`Connectors: ${model.connectors.join(", ") || "none"}`);
  console.log("Operations:");
  model.operations.forEach(op => console.log(`  ${op.method.padEnd(6)} ${op.path}`));
  console.log("=================================\n");
}

async function createProject(requirement) {
  let answers = {};
  let model = buildRequirementModel(requirement, answers);
  if (!model.operations.length) answers.operations = parseOperations(await ask("Which HTTP operations and paths are required?"));
  else answers.operations = model.operations;

  model = buildRequirementModel(requirement, answers);
  for (const item of missingQuestions(model)) {
    const value = await ask(item.question);
    if (item.key === "requestFields") answers.requestFields = list(value);
    if (item.key === "responseFields") answers.responseFields = list(value);
    if (item.key === "validation") answers.validation = list(value);
    if (item.key === "errors") answers.errors = list(value);
    if (item.key === "backend") answers.connectors = normalizeBackendConnectors(value);
    model = buildRequirementModel(requirement, answers);
  }

  answers.projectName = await ask("Project name", model.project.name);
  model = buildRequirementModel(requirement, answers);
  printDesign(model);
  const confirmed = (await ask("Generate this solution? (yes/no)", "yes")).toLowerCase();
  if (!/^(y|yes)$/.test(confirmed)) return { confirmed: false };

  const root = path.resolve(process.cwd(), model.project.name);
  if (fs.existsSync(root)) throw new Error(`Project already exists: ${model.project.name}`);
  fs.mkdirSync(root, { recursive: true });
  fs.writeFileSync(path.join(root, "muleforge.yaml"), YAML.stringify(model), "utf8");
  ["src/main/mule", "src/main/resources/api", "src/main/resources/dw", "src/test/munit"].forEach(dir => fs.mkdirSync(path.join(root, dir), { recursive: true }));
  writeDocumentation(root, model);
  fs.writeFileSync(path.join(root, "README.md"), `# ${model.project.name}\n\nGenerated by MuleForge from the confirmed requirement.\n\nSee [docs](docs/README.md).\n`, "utf8");

  console.log("\n✔ Requirement confirmed");
  console.log("✔ Project model written to muleforge.yaml");
  console.log("✔ Documentation generated under docs/");

  const generator = path.resolve(__dirname, "index.js");
  const generated = spawnSync(process.execPath, [generator, "generate", path.join(root, "muleforge.yaml")], {
    stdio: "inherit",
    cwd: root
  });
  if (generated.status !== 0) {
    throw new Error("Project generation failed. The project model was saved, but the complete Mule project could not be generated.");
  }

  const desktopCandidates = process.platform === "win32"
    ? [path.join(os.homedir(), "Desktop"), path.join(os.homedir(), "OneDrive", "Desktop")]
    : [path.join(os.homedir(), "Desktop")];
  const desktop = desktopCandidates.find(dir => fs.existsSync(dir));
  if (desktop) {
    const desktopRoot = path.join(desktop, model.project.name);
    if (path.resolve(desktopRoot) !== path.resolve(root)) {
      if (fs.existsSync(desktopRoot)) throw new Error(`Desktop project already exists: ${desktopRoot}`);
      fs.cpSync(root, desktopRoot, { recursive: true });
      console.log(`✔ Desktop project copy: ${desktopRoot}`);
    }
  } else {
    console.log("ℹ Desktop folder not found; project remains in the local project directory.");
  }

  console.log(`✔ Local project: ${root}`);
  console.log("✔ Complete Mule project is ready to open in Anypoint Studio");
  return { confirmed: true, root, model };
}

function registerCreate(program) {
  program.command("create [requirement]").description("Create a Mule project from a user requirement").action(async requirement => {
    try {
      await createProject(requirement || await ask("Describe what you want to build"));
    } catch (error) {
      console.error(`\n❌ ${error.message}`);
      process.exitCode = 1;
    }
  });
}

module.exports = { registerCreate, createProject, normalizeBackendConnectors };
