const fs = require("fs");
const path = require("path");
const readline = require("readline/promises");
const { stdin, stdout } = require("process");
const YAML = require("yaml");
const { buildRequirementModel, missingQuestions, writeDocumentation } = require("./requirement-model");

async function ask(question, fallback = "") {
  const rl = readline.createInterface({ input: stdin, output: stdout });
  const answer = (await rl.question(`${question}${fallback ? ` [${fallback}]` : ""}: `)).trim();
  rl.close();
  return answer || fallback;
}

const list = value => String(value || "").split(/,|\n/).map(v => v.trim()).filter(Boolean);
function parseOperations(value) {
  return list(value).map(item => {
    const m = item.match(/^(GET|POST|PUT|PATCH|DELETE)\s+(\/\S+)$/i);
    if (!m) throw new Error(`Invalid operation: ${item}. Use METHOD /path.`);
    return { method: m[1].toUpperCase(), path: m[2] };
  });
}

function printDesign(model) {
  console.log("\n=== MuleForge Solution Design ===");
  console.log(`Project: ${model.project.name}`);
  console.log(`API: ${model.api.type} ${model.api.basePath}`);
  console.log(`Connectors: ${model.connectors.join(", ") || "none"}`);
  console.log("Operations:");
  model.operations.forEach(op => console.log(`  ${op.method.padEnd(6)} ${op.path}`));
  console.log("=================================\n");
}

async function createProject(requirement) {
  let answers = {};
  let model = buildRequirementModel(requirement, answers);
  if (!model.operations.length) answers.operations = parseOperations(await ask("Which HTTP operations and paths are required?"));
  else answers.operations = model.operations;

  model = buildRequirementModel(requirement, answers);
  for (const item of missingQuestions(model)) {
    const value = await ask(item.question);
    if (item.key === "requestFields") answers.requestFields = list(value);
    if (item.key === "responseFields") answers.responseFields = list(value);
    if (item.key === "validation") answers.validation = list(value);
    if (item.key === "errors") answers.errors = list(value);
    if (item.key === "backend") answers.connectors = ["http", ...list(value).map(v => v.toLowerCase().replace(/\s+/g, "-"))];
    model = buildRequirementModel(requirement, answers);
  }

  answers.projectName = await ask("Project name", model.project.name);
  model = buildRequirementModel(requirement, answers);
  printDesign(model);
  const confirmed = (await ask("Generate this solution? (yes/no)", "yes")).toLowerCase();
  if (!/^(y|yes)$/.test(confirmed)) return { confirmed: false };

  const root = path.resolve(process.cwd(), model.project.name);
  if (fs.existsSync(root)) throw new Error(`Project already exists: ${model.project.name}`);
  fs.mkdirSync(root, { recursive: true });
  fs.writeFileSync(path.join(root, "muleforge.yaml"), YAML.stringify(model), "utf8");
  ["src/main/mule", "src/main/resources/api", "src/main/resources/dw", "src/test/munit"].forEach(dir => fs.mkdirSync(path.join(root, dir), { recursive: true }));
  writeDocumentation(root, model);
  fs.writeFileSync(path.join(root, "README.md"), `# ${model.project.name}\n\nGenerated by MuleForge from the confirmed requirement.\n\nSee [docs](docs/README.md).\n`, "utf8");
  console.log("\n✔ Requirement confirmed");
  console.log("✔ Project model written to muleforge.yaml");
  console.log("✔ Documentation generated under docs/");
  console.log("\nNext: muleforge generate");
  return { confirmed: true, root, model };
}

function registerCreate(program) {
  program.command("create [requirement]").description("Create a Mule project from a user requirement").action(async requirement => {
    try {
      await createProject(requirement || await ask("Describe what you want to build"));
    } catch (error) {
      console.error(`\n❌ ${error.message}`);
      process.exitCode = 1;
    }
  });
}

module.exports = { registerCreate, createProject };
