#!/usr/bin/env node

const { Command } = require("commander");
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");
const YAML = require("yaml");
const Handlebars = require("handlebars");

const VERSION = "0.2.0";
const program = new Command();

function write(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, "utf8");
}

function render(template, data) {
  return Handlebars.compile(template)(data);
}

function loadConfig(configPath = "muleforge.yaml") {
  const full = path.resolve(configPath);
  if (!fs.existsSync(full)) throw new Error(`Configuration not found: ${configPath}`);
  return YAML.parse(fs.readFileSync(full, "utf8"));
}

function context(config) {
  const project = config.project || {};
  return {
    projectName: project.name || "mule-api",
    artifactId: project.artifactId || project.name || "mule-api",
    groupId: project.groupId || "com.example",
    version: project.version || "1.0.0",
    muleRuntime: project.muleRuntime || "4.9.0"
  };
}

function generateProject(configPath = "muleforge.yaml") {
  const config = loadConfig(configPath);
  const data = context(config);
  const root = path.resolve(path.dirname(configPath));
  const templates = path.resolve(__dirname, "../templates");

  const pom = fs.readFileSync(path.join(templates, "pom.xml.hbs"), "utf8");
  const artifact = fs.readFileSync(path.join(templates, "mule-artifact.json.hbs"), "utf8");
  const munit = fs.readFileSync(path.join(templates, "munit/basic-test.xml.hbs"), "utf8");

  write(path.join(root, "pom.xml"), render(pom, data));
  write(path.join(root, "mule-artifact.json"), render(artifact, data));
  if ((config.testing || {}).munit !== false) {
    write(path.join(root, "src/test/munit", `${data.artifactId}-test.xml`), render(munit, data));
  }

  console.log(`✔ Generated pom.xml`);
  console.log(`✔ Generated mule-artifact.json`);
  if ((config.testing || {}).munit !== false) console.log(`✔ Generated MUnit test`);
  console.log(`🎉 ${data.projectName} generated successfully`);
}

function validate(configPath = "muleforge.yaml") {
  const config = loadConfig(configPath);
  const data = context(config);
  const root = path.resolve(path.dirname(configPath));
  const required = ["pom.xml", "mule-artifact.json", "src/main/resources/application.yaml"];
  const missing = required.filter((file) => !fs.existsSync(path.join(root, file)));

  console.log("\n🚀 MuleForge Validator\n");
  console.log(`✔ Configuration: ${configPath}`);
  console.log(`✔ Project: ${data.projectName}`);
  console.log(`✔ Mule runtime: ${data.muleRuntime}`);
  if (missing.length) {
    missing.forEach((file) => console.log(`✖ Missing: ${file}`));
    console.error(`\n${missing.length} problem(s) found.`);
    process.exitCode = 1;
    return;
  }
  console.log("✔ Maven project");
  console.log("✔ Mule artifact");
  console.log("✔ Application properties");
  console.log("\nValidation successful.\n");
}

function runMaven(args) {
  try {
    execFileSync(process.platform === "win32" ? "mvn.cmd" : "mvn", args, { stdio: "inherit" });
  } catch (error) {
    process.exitCode = error.status || 1;
  }
}

program.name("muleforge").description("Open-source Mule 4 API project generator").version(VERSION);

program.command("init <projectName>")
  .description("Create a MuleForge project skeleton")
  .action((projectName) => {
    const root = path.resolve(process.cwd(), projectName);
    if (fs.existsSync(root)) throw new Error(`Project already exists: ${projectName}`);
    fs.mkdirSync(root, { recursive: true });
    const config = `project:\n  name: ${projectName}\n  artifactId: ${projectName}\n  groupId: com.example\n  version: 1.0.0\n  muleRuntime: 4.9.0\n\napi:\n  name: ${projectName}\n  version: v1\n  specification: RAML\n  basePath: /api/v1\n\noperations:\n  - name: getCustomer\n    method: GET\n    path: /customers/{customerId}\n\n  - name: createCustomer\n    method: POST\n    path: /customers\n\ndatabase:\n  type: none\n\ntesting:\n  munit: true\n\ndeployment:\n  target: none\n`;
    write(path.join(root, "muleforge.yaml"), config);
    ["src/main/mule", "src/main/resources/api", "src/main/resources/dw", "src/test/munit", "database", ".github/workflows"].forEach((d) => fs.mkdirSync(path.join(root, d), { recursive: true }));
    write(path.join(root, "src/main/resources/application.yaml"), `http:\n  port: 8081\n\napi:\n  name: ${projectName}\n  version: v1\n`);
    write(path.join(root, "README.md"), `# ${projectName}\n\nGenerated by MuleForge.\n\n## Commands\n\n- muleforge generate\n- muleforge validate\n- muleforge build\n- muleforge test\n`);
    console.log(`\n🎉 Project created: ${projectName}`);
    console.log(`\nNext:\n  cd ${projectName}\n  muleforge generate\n  muleforge validate\n  muleforge build\n`);
  });

program.command("generate [config]").description("Generate missing Mule project files").action((config = "muleforge.yaml") => generateProject(config));
program.command("validate [config]").description("Validate a MuleForge project").action((config = "muleforge.yaml") => validate(config));
program.command("build").description("Build the Mule application with Maven").action(() => runMaven(["clean", "package"]));
program.command("test").description("Run Mule tests with Maven").action(() => runMaven(["test"]));
program.command("clean").description("Clean the Maven target directory").action(() => runMaven(["clean"]));
program.command("doctor").description("Check local Java and Maven tooling").action(() => {
  console.log("\n🚀 MuleForge Doctor\n");
  for (const command of ["java", "mvn"]) {
    try { execFileSync(command, ["-version"], { stdio: "inherit" }); console.log(`✔ ${command}`); }
    catch { console.log(`✖ ${command} not found`); }
  }
});

try { program.parse(); } catch (error) { console.error(`\n❌ ${error.message}`); process.exitCode = 1; }
