#!/usr/bin/env node

const { Command } = require("commander");
const fs = require("fs");
const path = require("path");

const program = new Command();

program
  .name("muleforge")
  .description("Open-source Mule 4 API project generator")
  .version("0.1.0");

function createFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

program
  .command("init <projectName>")
  .description("Initialize a new MuleForge project")
  .action((projectName) => {
    console.log("");
    console.log("🚀 MuleForge");
    console.log("");

    const projectPath = path.resolve(process.cwd(), projectName);

    if (fs.existsSync(projectPath)) {
      console.error(`❌ Project already exists: ${projectName}`);
      process.exit(1);
    }

    console.log(`Creating project: ${projectName}`);
    console.log("");

    // =========================================================
    // Create directories
    // =========================================================

    const directories = [
      "src/main/mule",
      "src/main/resources/api",
      "src/main/resources/dw",
      "src/test/munit",
      "database",
      ".github/workflows"
    ];

    directories.forEach((dir) => {
      fs.mkdirSync(path.join(projectPath, dir), {
        recursive: true
      });
    });

    // =========================================================
    // muleforge.yaml
    // =========================================================

    createFile(
      path.join(projectPath, "muleforge.yaml"),
      `project:
  name: ${projectName}
  version: 1.0.0

api:
  name: ${projectName}
  version: v1
  specification: RAML
  basePath: /api/v1

operations:
  - name: getCustomer
    method: GET
    path: /customers/{customerId}

  - name: createCustomer
    method: POST
    path: /customers

database:
  type: snowflake
  table: CUSTOMER

testing:
  munit: true

deployment:
  target: none
`
    );

    // =========================================================
    // mule-artifact.json
    // =========================================================

    createFile(
      path.join(projectPath, "mule-artifact.json"),
      `{
  "minMuleVersion": "4.9.0"
}
`
    );

    // =========================================================
    // README.md
    // =========================================================

    createFile(
      path.join(projectPath, "README.md"),
      `# ${projectName}

Generated by **MuleForge**.

## Project

This MuleSoft application was generated using MuleForge.

## Generate

\`\`\`bash
muleforge generate
\`\`\`

or

\`\`\`bash
muleforge generate muleforge.yaml
\`\`\`

## Build

\`\`\`bash
mvn clean package
\`\`\`

## Test

\`\`\`bash
mvn test
\`\`\`

## Run

Import the project into Anypoint Studio and run the Mule application.

## API

Base Path:

\`\`\`
/api/v1
\`\`\`

Customer endpoints:

\`\`\`
GET  /api/v1/customers
POST /api/v1/customers
GET  /api/v1/customers/{customerId}
\`\`\`
`
    );

    // =========================================================
    // RAML
    // =========================================================

    createFile(
      path.join(
        projectPath,
        "src/main/resources/api",
        `${projectName}.raml`
      ),
      `#%RAML 1.0

title: ${projectName}
version: v1
baseUri: /api/v1

/customers:

  get:
    description: Get customers
    responses:
      200:
        body:
          application/json:
            type: object

  post:
    description: Create customer
    body:
      application/json:
        type: object

    responses:
      201:
        body:
          application/json:
            type: object

  /{customerId}:

    get:
      description: Get customer by ID

      responses:

        200:
          body:
            application/json:
              type: object

        404:
          body:
            application/json:
              type: object
`
    );

    // =========================================================
    // Mule XML
    // =========================================================

    createFile(
      path.join(
        projectPath,
        "src/main/mule",
        `${projectName}.xml`
      ),
      `<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
      xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="
        http://www.mulesoft.org/schema/mule/core
        http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/http
        http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
        http://www.mulesoft.org/schema/mule/ee/core
        http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd">

    <http:listener-config
        name="HTTP_Listener_config"
        doc:name="HTTP Listener config">

        <http:listener-connection
            host="0.0.0.0"
            port="\${http.port}" />

    </http:listener-config>

    <flow name="${projectName}-flow">

        <http:listener
            config-ref="HTTP_Listener_config"
            path="/api/v1/customers"
            allowedMethods="GET,POST"
            doc:name="HTTP Listener" />

        <logger
            level="INFO"
            message="MuleForge generated API received request"
            doc:name="Logger" />

        <ee:transform doc:name="Transform Response">

            <ee:message>

                <ee:set-payload><![CDATA[
%dw 2.0
output application/json
---
{
    message: "MuleForge generated API is running",
    project: "${projectName}",
    version: "v1"
}
                ]]></ee:set-payload>

            </ee:message>

        </ee:transform>

    </flow>

</mule>
`
    );

    // =========================================================
    // Application properties
    // =========================================================

    createFile(
      path.join(
        projectPath,
        "src/main/resources",
        "application.yaml"
      ),
      `http:
  port: 8081

api:
  name: ${projectName}
  version: v1
`
    );

    // =========================================================
    // Maven POM
    // =========================================================

    createFile(
      path.join(projectPath, "pom.xml"),
      `<project xmlns="http://maven.apache.org/POM/4.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>com.muleforge</groupId>

  <artifactId>${projectName}</artifactId>

  <version>1.0.0</version>

  <packaging>mule-application</packaging>

  <name>${projectName}</name>

  <properties>

    <app.runtime>4.9.0</app.runtime>

    <mule.maven.plugin.version>4.3.0</mule.maven.plugin.version>

    <maven.compiler.source>17</maven.compiler.source>

    <maven.compiler.target>17</maven.compiler.target>

  </properties>

  <dependencies>

    <dependency>
      <groupId>org.mule.connectors</groupId>
      <artifactId>mule-http-connector</artifactId>
      <version>1.10.3</version>
      <classifier>mule-plugin</classifier>
    </dependency>

    <dependency>
      <groupId>org.mule.modules</groupId>
      <artifactId>mule-ee-module</artifactId>
      <version>1.3.0</version>
      <classifier>mule-plugin</classifier>
    </dependency>

  </dependencies>

  <build>

    <plugins>

      <plugin>

        <groupId>org.mule.tools.maven</groupId>

        <artifactId>mule-maven-plugin</artifactId>

        <version>\${mule.maven.plugin.version}</version>

        <extensions>true</extensions>

        <configuration>

          <runtimeVersion>\${app.runtime}</runtimeVersion>

        </configuration>

      </plugin>

    </plugins>

  </build>

</project>
`
    );

    // =========================================================
    // GitHub Actions
    // =========================================================

    createFile(
      path.join(
        projectPath,
        ".github/workflows",
        "build.yml"
      ),
      `name: MuleForge Build

on:
  push:
    branches:
      - main

  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Build Mule Application
        run: mvn clean package
`
    );

    // =========================================================
    // Success Messages
    // =========================================================

    console.log("✔ Project directory created");
    console.log("✔ MuleForge configuration created");
    console.log("✔ Mule artifact configuration created");
    console.log("✔ RAML specification created");
    console.log("✔ Mule flow created");
    console.log("✔ Application properties created");
    console.log("✔ Maven POM created");
    console.log("✔ GitHub Actions workflow created");
    console.log("✔ README created");

    console.log("");

    console.log("🎉 MuleForge project created successfully!");

    console.log("");

    console.log("Next steps:");
    console.log(`  cd ${projectName}`);
    console.log(`  muleforge generate`);
    console.log(`  mvn clean package`);

    console.log("");
  });

// =============================================================
// Generate Command
// =============================================================

program
  .command("generate [config]")
  .description("Generate a MuleSoft project")
  .action((config) => {
    console.log("");
    console.log("🚀 MuleForge Generator");
    console.log("");

    if (config) {
      console.log(`Configuration: ${config}`);
    } else {
      console.log("Using muleforge.yaml");
    }

    console.log("");

    // Future generator implementation
    console.log("✔ Configuration loaded");
    console.log("✔ Generation completed");

    console.log("");
  });

// =============================================================
// Parse CLI arguments
// =============================================================

program.parse();
