#!/usr/bin/env node

const { Command } = require("commander");
const fs = require("fs");
const path = require("path");

const program = new Command();

program
  .name("muleforge")
  .description("Open-source Mule 4 API project generator")
  .version("0.1.0");

function createFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

program
  .command("init <projectName>")
  .description("Initialize a new MuleForge project")
  .action((projectName) => {
    console.log("");
    console.log("🚀 MuleForge");
    console.log("");

    const projectPath = path.resolve(process.cwd(), projectName);

    if (fs.existsSync(projectPath)) {
      console.error(`❌ Project already exists: ${projectName}`);
      process.exit(1);
    }

    console.log(`Creating project: ${projectName}`);
    console.log("");

    // Create directories
    const directories = [
      "src/main/mule",
      "src/main/resources/api",
      "src/main/resources/dw",
      "src/test/munit",
      "database",
      ".github/workflows"
    ];

    directories.forEach((dir) => {
      fs.mkdirSync(path.join(projectPath, dir), {
        recursive: true
      });
    });

    // muleforge.yaml
    createFile(
      path.join(projectPath, "muleforge.yaml"),
      `project:
  name: ${projectName}
  version: 1.0.0

api:
  name: ${projectName}
  version: v1
  specification: RAML
  basePath: /api/v1

operations:
  - name: getCustomer
    method: GET
    path: /customers/{customerId}

  - name: createCustomer
    method: POST
    path: /customers

database:
  type: snowflake
  table: CUSTOMER

testing:
  munit: true

deployment:
  target: none
`
    );

    // README
    createFile(
      path.join(projectPath, "README.md"),
      `# ${projectName}

Generated by **MuleForge**.

## Project

This MuleSoft application was generated using MuleForge.

## Generate

\`\`\`bash
muleforge generate muleforge.yaml
\`\`\`

## Build

\`\`\`bash
mvn clean package
\`\`\`

## Test

\`\`\`bash
mvn test
\`\`\`
`
    );

    // RAML
    createFile(
      path.join(
        projectPath,
        "src/main/resources/api",
        `${projectName}.raml`
      ),
      `#%RAML 1.0
title: ${projectName}
version: v1
baseUri: /api/v1

/customers:
  get:
    responses:
      200:
        body:
          application/json:
            type: object

  post:
    body:
      application/json:
        type: object
    responses:
      201:
        body:
          application/json:
            type: object

  /{customerId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: object

        404:
          body:
            application/json:
              type: object
`
    );

    // Mule XML
    createFile(
      path.join(
        projectPath,
        "src/main/mule",
        `${projectName}.xml`
      ),
      `<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
      xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="
        http://www.mulesoft.org/schema/mule/core
        http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/http
        http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">

    <http:listener-config
        name="HTTP_Listener_config"
        doc:name="HTTP Listener config">

        <http:listener-connection
            host="0.0.0.0"
            port="\${http.port}" />

    </http:listener-config>

    <flow name="${projectName}-flow">

        <http:listener
            config-ref="HTTP_Listener_config"
            path="/api/v1/customers"
            allowedMethods="GET,POST"
            doc:name="HTTP Listener" />

        <logger
            level="INFO"
            message="MuleForge generated API received request"
            doc:name="Logger" />

        <ee:transform>
            <ee:message>
                <ee:set-payload><![CDATA[
%dw 2.0
output application/json
---
{
    message: "MuleForge generated API is running"
}
                ]]></ee:set-payload>
            </ee:message>
        </ee:transform>

    </flow>

</mule>
`
    );

    // Application properties
    createFile(
      path.join(
        projectPath,
        "src/main/resources",
        "application.yaml"
      ),
      `http:
  port: 8081

api:
  name: ${projectName}
  version: v1
`
    );

    // GitHub Actions
    createFile(
      path.join(
        projectPath,
        ".github/workflows",
        "build.yml"
      ),
      `name: MuleForge Build

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build
        run: mvn clean package
`
    );

    console.log("✔ Project directory created");
    console.log("✔ MuleForge configuration created");
    console.log("✔ RAML specification created");
    console.log("✔ Mule flow created");
    console.log("✔ Application properties created");
    console.log("✔ GitHub Actions workflow created");
    console.log("✔ README created");
    console.log("");
    console.log("🎉 MuleForge project created successfully!");
    console.log("");
    console.log(`Next steps:`);
    console.log(`  cd ${projectName}`);
    console.log(`  muleforge generate`);
    console.log("");
  });

program
  .command("generate [config]")
  .description("Generate a MuleSoft project")
  .action((config) => {
    console.log("");
    console.log("🚀 MuleForge Generator");
    console.log("");

    if (config) {
      console.log(`Configuration: ${config}`);
    } else {
      console.log("Using muleforge.yaml");
    }

    console.log("");
  });

program.parse();