const fs = require("fs");
const path = require("path");
const os = require("os");
const { execFileSync } = require("child_process");
const YAML = require("yaml");
const { writeDocumentation } = require("./requirement-model");
const { verifyProject } = require("./verify");

function safeName(value) {
  return String(value || "muleforge-project").trim().replace(/[^A-Za-z0-9._-]/g, "-").replace(/-+/g, "-") || "muleforge-project";
}

function desktopPath() {
  const candidates = [
    path.join(os.homedir(), "Desktop"),
    path.join(os.homedir(), "desktop"),
    path.join(process.env.USERPROFILE || os.homedir(), "Desktop")
  ];
  return candidates.find(p => fs.existsSync(p) && fs.statSync(p).isDirectory()) || null;
}

function runMuleForgeGenerate(configPath) {
  const cli = path.resolve(__dirname, "index.js");
  execFileSync(process.execPath, [cli, "generate", configPath], { stdio: "pipe", encoding: "utf8" });
}

function runMavenPackage(root) {
  const mvn = process.platform === "win32" ? "mvn.cmd" : "mvn";
  try {
    execFileSync(mvn, ["-B", "-DskipTests=false", "clean", "package"], {
      cwd: root,
      stdio: "pipe",
      encoding: "utf8"
    });
    return { pass: true, output: "Maven clean package passed." };
  } catch (error) {
    return {
      pass: false,
      output: String(error.stdout || "") + String(error.stderr || "") || `Maven package failed with exit code ${error.status || 1}.`
    };
  }
}

function copyDirectory(source, destination) {
  fs.mkdirSync(destination, { recursive: true });
  fs.cpSync(source, destination, { recursive: true, force: true });
}

function prepareAndSave(model) {
  const desktop = desktopPath();
  if (!desktop) {
    throw new Error("Desktop folder was not found. Nothing was saved.");
  }

  const projectName = safeName(model.project?.name);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), "muleforge-"));
  const stagedRoot = path.join(tempRoot, projectName);
  const configPath = path.join(stagedRoot, "muleforge.yaml");

  try {
    fs.mkdirSync(stagedRoot, { recursive: true });
    fs.writeFileSync(configPath, YAML.stringify(model), "utf8");
    writeDocumentation(stagedRoot, model);
    fs.writeFileSync(
      path.join(stagedRoot, "README.md"),
      `# ${projectName}\n\nGenerated by MuleForge from the confirmed requirement.\n\nSee [docs](docs/README.md).\n`,
      "utf8"
    );

    // Generation happens only in the temporary staging directory.
    runMuleForgeGenerate(configPath);

    // Nothing reaches Desktop until static verification AND Maven tests pass.
    const verification = verifyProject(configPath, { build: true });
    if (!verification.ready) {
      const failed = verification.failed.map(x => x.name).join(", ");
      throw new Error(`Generation gate failed. Nothing was saved to Desktop. Failed checks: ${failed || "Maven tests"}`);
    }

    // Final package gate protects the exported project from a broken artifact.
    const packageResult = runMavenPackage(stagedRoot);
    if (!packageResult.pass) {
      throw new Error(`Maven package gate failed. Nothing was saved to Desktop.\n${packageResult.output}`);
    }

    const destination = path.join(desktop, projectName);
    if (fs.existsSync(destination)) {
      throw new Error(`Desktop already contains "${projectName}". Nothing was overwritten.`);
    }

    // Atomic-ish final handoff: only this copy is performed after every gate passes.
    copyDirectory(stagedRoot, destination);
    return {
      saved: true,
      projectName,
      path: destination,
      verification: {
        score: verification.score,
        passed: verification.passed,
        total: verification.total,
        mavenTests: verification.build.pass,
        package: packageResult.pass
      }
    };
  } finally {
    fs.rmSync(tempRoot, { recursive: true, force: true });
  }
}

module.exports = { prepareAndSave, desktopPath, safeName };
