<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.muleforge.examples</groupId>
  <artifactId>customer-api</artifactId>
  <version>1.0.0</version>
  <packaging>mule-application</packaging>

  <properties>
    <app.runtime>4.9.0</app.runtime>
    <mule.maven.plugin.version>4.3.0</mule.maven.plugin.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <cloudhub2.applicationName>customer-api-dev</cloudhub2.applicationName>
    <cloudhub2.environment>Development</cloudhub2.environment>
    <cloudhub2.target>CloudHub-US-East-2</cloudhub2.target>
    <cloudhub2.provider>MC</cloudhub2.provider>
    <cloudhub2.muleVersion>4.9.0</cloudhub2.muleVersion>
    <cloudhub2.replicas>1</cloudhub2.replicas>
    <cloudhub2.vCores>0.1</cloudhub2.vCores>
  </properties>

  <repositories>
    <repository>
      <id>anypoint-exchange</id>
      <name>Anypoint Exchange</name>
      <url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
      <layout>default</layout>
    </repository>
    <repository>
      <id>mulesoft-releases</id>
      <name>MuleSoft Releases Repository</name>
      <url>https://repository.mulesoft.org/releases/</url>
      <layout>default</layout>
    </repository>
    <repository>
      <id>mulesoft-public</id>
      <name>MuleSoft Public Repository</name>
      <url>https://repository.mulesoft.org/nexus/content/repositories/public/</url>
      <layout>default</layout>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>mulesoft-releases</id>
      <name>MuleSoft Releases Repository</name>
      <url>https://repository.mulesoft.org/releases/</url>
      <layout>default</layout>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

  <distributionManagement>
    <repository>
      <id>anypoint-exchange</id>
      <name>Anypoint Exchange</name>
      <url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${env.ANYPOINT_ORG_ID}/maven</url>
    </repository>
  </distributionManagement>

  <dependencies>
    <dependency>
      <groupId>org.mule.connectors</groupId>
      <artifactId>mule-db-connector</artifactId>
      <version>1.14.13</version>
      <classifier>mule-plugin</classifier>
    </dependency>
    <dependency>
      <groupId>net.snowflake</groupId>
      <artifactId>snowflake-jdbc</artifactId>
      <version>3.20.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.mule.tools.maven</groupId>
        <artifactId>mule-maven-plugin</artifactId>
        <version>${mule.maven.plugin.version}</version>
        <extensions>true</extensions>
        <configuration>
          <cloudhub2Deployment>
            <uri>https://anypoint.mulesoft.com</uri>
            <applicationName>${cloudhub2.applicationName}</applicationName>
            <environment>${cloudhub2.environment}</environment>
            <target>${cloudhub2.target}</target>
            <provider>${cloudhub2.provider}</provider>
            <muleVersion>${cloudhub2.muleVersion}</muleVersion>
            <replicas>${cloudhub2.replicas}</replicas>
            <vCores>${cloudhub2.vCores}</vCores>
            <connectedAppClientId>${env.ANYPOINT_CLIENT_ID}</connectedAppClientId>
            <connectedAppClientSecret>${env.ANYPOINT_CLIENT_SECRET}</connectedAppClientSecret>
            <connectedAppGrantType>client_credentials</connectedAppGrantType>
          </cloudhub2Deployment>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
